GAME_DIRS='./erasure'

help:
	@echo 'Usage:'
	@echo '    BUILD COMMANDS'
	@echo '    make help       - show this message'
	@echo
	@echo '    TESTING COMMANDS'
	@echo '    make test       - run tests for all components'
	@echo '    make lint       - run code analysis on all components'

test:
	@echo 'Not implemented!'

lint:
	@echo 'Not implemented!'

.PHONY: help test lint 
